version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "build"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
